config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :list_furnitures
  resources :list_arts
  resources :list_sells
  resources :rental_lists
  mount ActionCable.server => '/cable'
  
  resources :notifications
  resources :profiles
  resources :properties
  devise_for :users
  resources :user do
    resources :services do
      member do
        post "mark_as_favorite"
      end
    end
  end
  root 'home#index'
  resources :chats, only: [:index, :show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'realtors' => 'pages#agents'
  get 'single_agent' => 'pages#single_agent'
  get 'list_rental' => 'pages#list_rental'
  get 'submit_property' => 'pages#submit_property'
  get 'property' => 'pages#property'
  get 'blog' => 'pages#blog'
  get 'single_blog' => 'pages#single_blog'
  get 'my_profile' => 'pages#my_profile'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'services' => 'pages#services'
  get 'my_property' => 'pages#my_property'
  get 'coming_soon' => 'pages#coming_soon'
  get 'book_marked_listing' => 'pages#book_marked_listing'
  get 'buy' => 'pages#buy'
  get 'sell' => 'pages#sell'
  get 'rent' => 'pages#rent'
  get 'property_detail' => 'pages#property_detail'
  get 'mortgage' => 'pages#mortgage' 
  get 'insurance' => 'pages#insurance' 
  get 'mobileApps' => 'pages#mobile_apps' 
  get 'hotels' => 'pages#hotels' 
  get 'partners' => 'pages#partners' 
  get 'investors' => 'pages#investors' 
  get 'team' => 'pages#team' 
  get 'travel' => 'pages#travel'
  get 'list_new' => 'pages#list_new'
  get '/buy/search' => 'pages#buy_search'
  get '/rent/search' => 'pages#rent_search'
  get '/services/search' => 'pages#services_search'
  get '/find-friend' => 'profiles#find_friends'
  get '/friend_list' => 'profiles#friend_list'
  post "profiles/add_friend" => "profiles#add_friend"
  post "profiles/remove_friend" => "profiles#remove_friend"
  get "/inbox" => "profiles#messages"
  get "art" => "pages#art"
  get "furniture" => "pages#furniture"
  post "switch_role" => "services#switch_role"

  get "/privacy-policy" => "pages#privacy_policy"
  get "/term_of_use" => "pages#term_of_use"
  get "/cookies-policy" => "pages#cookies_policy"

  resources :messages, only:[:create]
end

app/models/service.rb
class Service < ApplicationRecord
	resourcify
	has_many_attached :images, dependent: :destroy
	has_many :requirements, dependent: :destroy
	has_many :faqs, dependent: :destroy
	has_many :packages, dependent: :destroy
	
	belongs_to :user
	has_many :favorites, dependent: :destroy
  has_many :users_favorites, through: :favorites, source: :user

	accepts_nested_attributes_for :packages, reject_if: proc { |attributes| attributes['name'].blank? }
	accepts_nested_attributes_for :faqs, reject_if: proc { |attributes| attributes['question'].blank? }
	accepts_nested_attributes_for :requirements, reject_if: proc { |attributes| attributes['description'].blank? }

	validates_presence_of :packages
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :edit, :switch_role, :mark_as_favorite]
  before_action :authenticate_user!

  # GET /services
  # GET /services.json
  def index
    @user = current_user
    @services = current_user.services
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @user = current_user
    if current_user.profile.present?
      @service = @user.services.build
      @service.packages.build
      @service.requirements.build
      @service.faqs.build
    else
      redirect_to new_profile_url
    end
  end

  # GET /services/1/edit
  def edit
    @user = current_user
  end

  # POST /services
  # POST /services.json
  def create
    @user = current_user
    @service = current_user.services.new(service_params)
    @service.tags = service_params['tags'].split

    respond_to do |format|
      if @service.save
        # format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.html { redirect_to user_services_path(current_user), notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to user_services_path(current_user), notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to user_services_path(current_user), notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def switch_role
    if @user.has_role?(:seller)
      @user.remove_role(:seller)
      @user.add_role(:buyer)
      redirect_to '/services'
      puts "switched the role to Buyer"
    else
      @user.remove_role(:buyer)
      @user.add_role(:seller)
      redirect_to user_services_path(current_user)
      puts "switched the role to Seller"
    end
  end

  def mark_as_favorite
    @services = Service.take(4)
    if @user.favorites.find_by(service_id: params[:id]).nil?
      @user.favorites.create(service_id: params[:id])
    else
      @user.favorites.find_by(service_id: params[:id]).delete
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = current_user.services.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      # params.fetch(:service, {})
      params.require(:service).permit(:title, :category, :price, :tags, :description,
                                      packages_attributes: [:name, :description, :delivery_time,
                                      :revisions, :price, :service],
                                      requirements_attributes: [:description, :requirement_type, :is_mandatory],
                                      faqs_attributes: [:question, :answer])
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_faq_fields.html.erb
<div class="submit-property__block">
  <div class="row">
      <div class="col-md-6">
          <div class="submit-property__group">
              <label for="property-price" class="submit-property__label">Question *</label>
              <%= f.text_field :question, class: "submit-property__field"%>
              <span class="submit-property__unit"></span>
          </div><!-- .submit-property__group -->
      </div><!-- .col -->                              

  </div><!-- .row -->

  <div class="row">
      <div class="col-md-6">
        <div class="submit-property__group">
            <label for="property-price" class="submit-property__label">Answer *</label>
            <%= f.text_area :answer, class: "submit-property__field"%>
            <span class="submit-property__unit"></span>
        </div><!-- .submit-property__group -->
      </div><!-- .col -->                              

  </div><!-- .row -->
</div><!-- .submit-property__block -->

app/views/services/_form.html.erb
<%= form_with(model: [@user, @service], local: true) do |form| %>
  <div class="col-md-9">
      <% if @service.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

          <ul>
          <% @service.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="submit-property__block">
          <h3 class="submit-property__headline">Basic Information</h3>
          <div class="submit-property__group">
              <label for="title" class="submit-property__label">Service Title *</label>
              <%= form.text_field :title, class: "submit-property__field", placeholder: placeholder="I will clean your home", :required => true, :maxlength => 25, :size => 40%>
              
          </div>

          <div class="row">
              <div class="col-md-6">
                  <div class="submit-property__group">
                      <label for="property-type" class="submit-property__label">Service Category *</label>
                      <%= form.select(:category, options_for_select(["Assembly", "Carpet Cleaning", "Electrical", "House Cleaning", "HVAC", "Handyman", "IT", "Junk Removal", "Lawn Care","Moving", "Painting", "Plumbing", "Staging", "Photography", "Videography", "Inspectors"], :selected => form.object.category), {include_blank: false}, { :class => 'ht-field' }) %>
                  </div>
              </div><!-- .col -->

              <div class="col-md-6">
                  <div class="submit-property__group">
                      <label for="property-price" class="submit-property__label">Tags *</label>
                      <%= form.text_field :tags, class: "submit-property__field", required: true%>
                      <span class="submit-property__unit"></span>
                  </div><!-- .submit-property__group -->
              </div><!-- .col -->
          </div><!-- .row -->

          <div class="submit-property__group">
              <label for="submit-property-wysiwyg" class="submit-property__label">Description *</label>
              <%= form.text_area :description, id: "submit-property-wysiwyg", required: true %>
          </div><!-- .submit-property__group -->
      </div><!-- .submit-property__block -->

      <div class="submit-property__block">
          <h3 class="submit-property__headline">Gallery or Video</h3>
          
          <div class="row">
              <div class="col-md-5">
                  <div class="submit-property__group">
                      <label for="property-featured-image" class="submit-property__label">Featured Image *</label>
                      <div class="submit-property__upload">
                          <input type="file">
                          <div class="submit-property__upload-inner">
                              <span class="ion-ios-plus-outline submit-property__icon"></span>
                              <span class="submit-property__upload-desc">Drop image here or click to upload</span>
                          </div>
                      </div><!-- .submit-proeprty__upload -->
                  </div><!-- .submit-property__group -->
              </div><!-- .col -->

              <div class="col-md-7">
                  <div class="submit-property__group">
                      <label for="property-media" class="submit-property__label">All Images or Video </label>
                      <div class="submit-property__upload">
                          <input type="file" multiple>
                          <div class="submit-property__upload-inner">
                              <span class="ion-ios-plus-outline submit-property__icon"></span>
                              <span class="submit-property__upload-desc">Drop all images here or click to upload</span>
                          </div>
                      </div><!-- .submit-proeprty__upload -->
                  </div><!-- .submit-property__group -->
              </div><!-- .col -->
          </div><!-- .row -->
      </div><!-- .submit-property__block -->

      <h3 class="submit-property__headline">Packages
        <span id="package-toggle" class="toggle">
          <span class="toggle-switch"></span>
        </span>
      </h3>
      <div id="packages" class="block-ianctive">
        <%= form.fields_for :packages do |package| %>
          <%= render 'package_fields', :f => package %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'Add another', form, :packages %>
        </div>
      </div>


      <h3 class="submit-property__headline">Requirements
        <span id="requirement-toggle" class="toggle">
          <span class="toggle-switch"></span>
        </span>
      </h3>
      <div id="requirements" class="block-ianctive">
        <%= form.fields_for :requirements do |requirement| %>
          <%= render 'requirement_fields', :f => requirement %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'Add another', form, :requirements %>
        </div>
      </div>

      <h3 class="submit-property__headline">FAQs
        <span id="faq-toggle" class="toggle">
          <span class="toggle-switch"></span>
        </span>
      </h3>
      <div id="faqs" class="block-ianctive">
        <%= form.fields_for :faqs do |faq| %>
          <%= render 'faq_fields', :f => faq %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'Add another', form, :faqs %>
        </div>
      </div>

      <button type="submit" class="submit-property__submit" style="background-color: #ED4737">Submit</button>

  </div>
<% end %>

app/views/services/_index.html.erb
<section style="margin-top: 50px">
  <h2 style="margin-left: 15px; padding-bottom: 30px; font-size: 24px;">Recently viewed & more</h2>
  <% @services.each do |service| %>
    <%= render 'services/service_card', :f => service %>
  <% end %>
</section>

<section class="jumbotron"style="margin-top: 50px">
  <h2 style="margin-left: 15px; padding-bottom: 30px; font-size: 24px;">Pro SEM services
  </h2>
  <% @services.each do |service| %>
    <%= render 'services/service_card', :f => service %>
  <% end %>
</section>


<section style="margin-top: 50px">
  <h2 style="margin-left: 15px; padding-bottom: 30px; font-size: 24px;">Similar to services you've viewed
  </h2>
  <% @services.each do |service| %>
    <%= render 'services/service_card', :f => service %>
  <% end %>
</section>

app/views/services/_listing_sidebar.html.erb
<div class="col-md-3">


<div class="settings-block">
    <span class="settings-block__title">Manage Listing</span>
    <ul class="settings">
        <li class="setting <%= cp(new_user_service_path)%>"><a href="<%= new_user_service_path %>" class="setting__link"><i class="ion-ios-plus-outline setting__icon"></i>New Service Listing</a></li>
        <li class="setting <%= cp(user_services_path)%>"><a href="<%= user_services_path %>" class="setting__link"><i class="ion-ios-home-outline setting__icon"></i>My Listings</a></li>
        <li class="setting"><a href="/list_new" class="setting__link"><i class="ion-ios-undo-outline setting__icon"></i>Back</a></li>
    </ul>
</div>


</div>

app/views/services/_package_fields.html.erb
<div class="submit-property__block">
  <!-- Rounded switch -->
  <div class="submit-property__group">
      <label for="title" class="submit-property__label">Package Name *</label>
      <%= f.text_field :name, class: "submit-property__field", placeholder: placeholder="Basic"%> 
  </div>

  <div class="row">
      <div class="col-md-4">
          <div class="submit-property__group">
              <label for="property-price" class="submit-property__label">Price *</label>
              <%= f.text_field :price, class: "submit-property__field"%>
              <span class="submit-property__unit">USD</span>
          </div><!-- .submit-property__group -->
      </div><!-- .col -->                

      <div class="col-md-4">
        <div class="submit-property__group">
            <label for="property-type" class="submit-property__label">Revisions *</label>
            <%= f.select(:revisions, options_for_select((1..20), :selected => f.object.revisions), { :class => 'ht-field' }) %>
        </div>
      </div><!-- .col -->

      <div class="col-md-4">
        <div class="submit-property__group">
            <label for="property-type" class="submit-property__label">Delivery Time(Days) *</label>
            <%= f.select(:delivery_time, options_for_select((1..20), :selected => f.object.delivery_time), { :class => 'ht-field' }) %>
        </div>
      </div><!-- .col -->
  </div><!-- .row -->

  <div class="submit-property__group">
      <label for="property-price" class="submit-property__label">Description *</label>
      <%= f.text_area :description, class: "submit-property__field"%>
      <span class="submit-property__unit"></span>
  </div><!-- .submit-property__group -->

</div><!-- .submit-property__block -->

app/views/services/_requirement_fields.html.erb
<div class="submit-property__block">
  <div class="submit-property__group">
    <label for="property-price" class="submit-property__label">Description *</label>
    <%= f.text_area :description, class: "submit-property__field"%>
    <span class="submit-property__unit"></span>
  </div><!-- .submit-property__group -->

  <div class="row">
    <div class="col-md-4">
      <div class="submit-property__group">
          <label for="property-price" class="submit-property__label">Type *</label>
          <%= f.select(:requirement_type, options_for_select(["Text", "Multiple Choice"], :selected => f.object.requirement_type), {include_blank: false}, { :class => 'ht-field' }) %>
          <span class="submit-property__unit"></span>
      </div><!-- .submit-property__group -->
    </div><!-- .col -->                

  </div><!-- .row -->

  <div class="submit-property__group">
    <label for="submit-property-wysiwyg" class="submit-property__label">Mandatory *</label>
    <%= f.check_box :is_mandatory, id: "submit-property-wysiwyg"%>
  </div><!-- .submit-property__group -->
</div><!-- .submit-property__block -->

app/views/services/_service_card.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3" style="padding-bottom: 10px">
    <div class="boxes">
      <div class="box-img">
        <img src="<%= asset_path( 'MobileApps.png' ) %>">
      </div>
      <div class="user-detail-main">
        <div class="user-detail-img">
          <img src="<%= asset_path( 'MobileApps.png' ) %>">
        </div>
        <div class="user-detail">
          <a><h3><%= f.user.profile.first.first_name %></h3></a>
          <p>Level 1 Seller</p>
        </div>
        <div class="user-detail-para">
          <p><%= f.description %></p>
        </div>
        <div style="padding-top: 50px;">
          <i class="fas fa-star" style="color: #ffbf00"></i> (5)
        </div>
      </div>
      <div class="user-detail-footer">
        <div class="heart-icon">
          <%= link_to mark_as_favorite_user_service_path(f.user, f), method: :post, remote: true do %>
            <i class="fas fa-heart" style="<%= f.favorites.find_by(user_id: current_user.id).nil? ? "color: #c6c6c6" : "color: black"%>"></i>
          <% end %>
          <i class="fas fa-bars" style="color: #c6c6c6"></i>
        </div>
        <div class="user-value">
          <p>Starting At $ <%= f.packages.first.price%></p>
        </div>
      </div>
    </div>
</div>

app/views/services/edit.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
        <%= render 'listing_sidebar' %>
        <%= render 'form', service: @service %>
      </div>
    </div>
  </div>
</section>

app/views/services/index.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
      <%= render 'listing_sidebar' %>
        <div class="col-md-9">
          <ul class="manage-list manage-list--my-property">
            <li class="manage-list__header">
              <span class="manage-list__title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> My List</span>
              <span class="manage-list__title"><i class="fa fa-calendar-o" aria-hidden="true"></i> Creation Date</span>
            </li>
            <% @services.each do |service| %>
              <li class="manage-list__item">
              <div class="manage-list__item-container">
                <div class="manage-list__item-img">
                    <%= image_tag 'uploads/manage-item-1.jpg', alt: 'Weston Hightpointe Place', class: 'listing__img'%>
                </div><!-- manage-list__item-img -->
          
                <div class="manage-list__item-detail">
                  <h3 class="listing__title"><a href="#"><%= service.title %></a></h3>
                </div>
              </div><!-- .manage-list__item-container -->
              <div class="manage-list__expire-date"><%= service.created_at.to_date %></div>
              
              <div class="manage-list__action">
                <td><%= link_to '<span class="edit"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</span>'.html_safe, edit_user_service_path(@user, service) %></td>
                <%= link_to '<span class="remove"><i class="fa fa-times" aria-hidden="true"></i>Remove</span>'.html_safe, user_service_path(@user, service), method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </li><!-- .manage-list__item" -->
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/services/index.js.erb
$('#services').html("<%= j (render 'services/index') %>");

app/views/services/mark_as_favorite.js.erb
$('#services').html("<%= j (render 'pages/services') %>");

app/views/services/new.html.erb
<% if can? :manage, @service %>
  <section class="my-property">
    <div class="container">
      <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
        <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
        <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
        <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
      </ul>
      <div class="my-profile__container">
        <div class="row">
          <%= render 'listing_sidebar' %>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <section class="my-property">
    <div class="container">
      <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
        <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
        <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
        <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
      </ul>
      <div class="my-profile__container">
        <div style="text-align: center" class="row">
          <h3 style="padding-bottom: 20px;">You are currently in the buyer mode</h3>
          <%= link_to "Switch To Seller", switch_role_path, method: :post  %>    
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/services/packages.html.erb
<% f.each do |service| %>
  <%= render 'services/service_card', :f => service %>
<% end %>

app/views/services/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>
 -->