config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :list_furnitures
  resources :list_arts
  resources :list_sells
  resources :rental_lists
  mount ActionCable.server => '/cable'
  
  resources :notifications
  resources :profiles
  resources :properties
  devise_for :users
  resources :user do
    resources :services do
      member do
        post "mark_as_favorite"
      end
    end
  end
  root 'home#index'
  resources :chats, only: [:index, :show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'realtors' => 'pages#agents'
  get 'single_agent' => 'pages#single_agent'
  get 'list_rental' => 'pages#list_rental'
  get 'submit_property' => 'pages#submit_property'
  get 'property' => 'pages#property'
  get 'blog' => 'pages#blog'
  get 'single_blog' => 'pages#single_blog'
  get 'my_profile' => 'pages#my_profile'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'services' => 'pages#services'
  get 'my_property' => 'pages#my_property'
  get 'coming_soon' => 'pages#coming_soon'
  get 'book_marked_listing' => 'pages#book_marked_listing'
  get 'buy' => 'pages#buy'
  get 'sell' => 'pages#sell'
  get 'rent' => 'pages#rent'
  get 'property_detail' => 'pages#property_detail'
  get 'mortgage' => 'pages#mortgage' 
  get 'insurance' => 'pages#insurance' 
  get 'mobileApps' => 'pages#mobile_apps' 
  get 'hotels' => 'pages#hotels' 
  get 'partners' => 'pages#partners' 
  get 'investors' => 'pages#investors' 
  get 'team' => 'pages#team' 
  get 'travel' => 'pages#travel'
  get 'list_new' => 'pages#list_new'
  get '/buy/search' => 'pages#buy_search'
  get '/rent/search' => 'pages#rent_search'
  get '/services/search' => 'pages#services_search'
  get '/find-friend' => 'profiles#find_friends'
  get '/friend_list' => 'profiles#friend_list'
  post "profiles/add_friend" => "profiles#add_friend"
  post "profiles/remove_friend" => "profiles#remove_friend"
  get "/inbox" => "profiles#messages"
  get "art" => "pages#art"
  get "furniture" => "pages#furniture"
  post "switch_role" => "services#switch_role"

  get "/privacy-policy" => "pages#privacy_policy"
  get "/term_of_use" => "pages#term_of_use"
  get "/cookies-policy" => "pages#cookies_policy"

  resources :messages, only:[:create]
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :property_type, :offer, :rental_period, :property_price, :propert_area, :property_room, :description, :google_map_address, :friendly_address, :longtitude, :latitude, :region, :building_year, :bedrooms, :bathrooms, :lot_size, :parking, :cooling, :sewer, :water, :exersie_room)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_property_content.html.erb
<main class="col-md-9">
  <div class="property__feature-container">
    <div class="property__slider property__slider--v2">
        <div class="property__slider-container">
          
          <div class="property__slider-main">
            <div class="property__slider-images">
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
               <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
               <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
               <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
  
              <div class="property__slider-image">
                <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
              </div><!-- .property__slider-image -->
            </div><!-- .property__slider-images -->
  
            <ul class="image-navigation">
              <li class="image-navigation__prev">
                <span class="ion-ios-arrow-left"></span>
              </li>
              <li class="image-navigation__next">
                <span class="ion-ios-arrow-right"></span>
              </li>
            </ul>
  
            <span class="property__slider-info"><i class="ion-android-camera"></i><span class="sliderInfo"></span></span>
          </div><!-- .property__slider-main -->

          <ul class="property__slider-nav property__slider-nav--horizontal">
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
             <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
  
            <li class="property__slider-item">
              <%= image_tag 'uploads/slider.jpeg', alt: 'Image 1'%>
            </li><!-- .property__slider-item -->
          </ul><!-- .property__slider-nav -->
        </div><!-- .property__slider-container -->
      </div><!-- .property__slider -->


    <div class="property__feature">
      <h3 class="property__feature-title property__feature-title--b-spacing">Property Description</h3>
      <%= property.description.html_safe %>

    </div><!-- .property__feature -->

    <div class="property__feature">
      <h3 class="property__feature-title property__feature-title--b-spacing">Property Details</h3>
      <ul class="property__details-list">
        <li class="property__details-item"><span class="property__details-item--cat"> Property Type: </span><%= property.property_type.capitalize! %></li>
        <li class="property__details-item"><span class="property__details-item--cat">Year Built:</span> <%= property.building_year %></li>
        <li class="property__details-item"><span class="property__details-item--cat">Water: </span> 
         <%= property.water %> </li>
         <li class="property__details-item"><span class="property__details-item--cat">Cooling: </span> 
         <%= property.cooling %> </li>
         <li class="property__details-item"><span class="property__details-item--cat">Sewer: </span> 
         <%= property.sewer %> </li>
         <li class="property__details-item"><span class="property__details-item--cat">Parking: </span> 
         <%= property.parking %> </li>
         <li class="property__details-item"><span class="property__details-item--cat">Exersice Room:</span> 
         <%= property.exersie_room %> </li>
        <li class="property__details-item"><span class="property__details-item--cat">Lot size:</span> <%= property.lot_size%></li>
      </ul><!-- .property__details-list -->
    </div><!-- .property__feature -->

    <div class="property__feature">
      <h3 class="property__feature-title property__feature-title--b-spacing">Property Features</h3>
      <ul class="property__features-list">
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Air Conditioning</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Barbeque</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Dryer</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Gym</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Laundry</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Lawn</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Microwave</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Outdoor Shower</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Refrigerator</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Sauna</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Swimming Pool</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>TV Cable</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Washer</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Wifi</li>
        <li class="property__features-item"><span class="property__features-icon ion-checkmark-round"></span>Window Coverings</li>
      </ul><!-- .property__features-list -->
    </div><!-- .property__feature -->
  </div><!-- .property__feature-container -->
</main>

app/views/properties/_property_content_header.html.erb
<div class="property__header">
  <div class="container">
    <div class="property__header-container">
      <ul class="property__main">
        <li class="property__title property__main-item">
          <div class="property__meta">
            <span class="property__offer">For <%= property.offer%></span>
          </div><!-- .property__meta -->
          <h2 class="property__name"> <%= property.title%></h2>
          <span class="property__address"><i class="ion-ios-location-outline property__address-icon"></i>
          <%= property.friendly_address%>
          </span>
        </li>
        <li class="property__details property__main-item">
          <ul class="property__stats">
            <li class="property__stat"><span class="property__figure"><%= property.bedrooms%></span> Beds</li>
            <li class="property__stat"><span class="property__figure"><%= property.bathrooms%></span> Baths</li>
            <li class="property__stat"><span class="property__figure"><%= property.propert_area%></span> sq.ft</li>
          </ul><!-- .listing__stats -->
        </li>
        <li class="property__price property__main-item">
          <h4 class="property__price-primary">$<%= property.property_price%></h4>
          <span class="property__price-secondary">$4,824/sq.ft</span>
        </li>
      </ul><!-- .property__main -->

      <ul class="property__list">
        <li class="property__item">
          <a href="<%= edit_property_path(property)%>" class="property__link">
            <i class="icon ion-edit property__icon" ></i>  
            <span class="property__item-desc">Edit</span>
          </a>
        </li>
        <li class="property__item">
          <a href="<%= properties_path%>" class="property__link">
            <i class="icon ion-arrow-left-a property__icon"></i>
            <span class="property__item-desc">Back</span>
          </a>
        </li>
      </ul><!-- .property__list -->
    </div><!-- .property__header-container -->
  </div><!-- .container -->
</div><!-- .property__header -->s

app/views/properties/edit.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
        <%= render 'partial/profile_sidebar' %>
        <%= render 'form', property: @property %>        
      </div>
    </div>
  </div>
</section>  

app/views/properties/index.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
        <%= render 'partial/profile_sidebar' %>
        <div class="col-md-9">
          <ul class="manage-list manage-list--my-property">
            <li class="manage-list__header">
              <span class="manage-list__title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> My Property</span>
              <span class="manage-list__title"><i class="fa fa-calendar-o" aria-hidden="true"></i> Creation Date</span>
            </li>

            <% @properties.each do |property| %>
              <li class="manage-list__item">
              <div class="manage-list__item-container">
                <div class="manage-list__item-img">
                    <%= image_tag 'uploads/manage-item-1.jpg', alt: 'Weston Hightpointe Place', class: 'listing__img'%>
                </div><!-- manage-list__item-img -->
          
                <div class="manage-list__item-detail">
                  <h3 class="listing__title"><a href="<%= property_path(property) %>"><%= property.title %></a></h3>
                  <p class="listing__location"><span class="ion-ios-location-outline listing__location-icon"><%= property.friendly_address %></span> </p>
                  <p class="listing__price"><%= property.property_price %></p>
                </div>
              </div><!-- .manage-list__item-container -->
              <div class="manage-list__expire-date"><%= property.created_at.to_date %></div>
              
              <div class="manage-list__action">
                <td><%= link_to '<span class="edit"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</span>'.html_safe, edit_property_path(property) %></td>
                <%= link_to '<span class="remove"><i class="fa fa-times" aria-hidden="true"></i>Remove</span>'.html_safe, property, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </li><!-- .manage-list__item" -->
            <% end %>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/properties/new.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Pages</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">My Profile</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
        <%= render 'partial/profile_sidebar' %>
        <%= render 'form', property: @property %>        
      </div>
    </div>
  </div>
</section>  

app/views/properties/show.html.erb
<section class="property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="#" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Property</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">Single Property V2</span></li>
    </ul><!-- ht-breadcrumb -->
  </div><!-- .container -->

  <%= render 'property_content_header', property: @property %>

  <div class="property__container">
    <div class="container">
      <div class="row">
        <%= render 'property_content' , property: @property %>

        <aside class="col-md-3">
          <div class="widget__container">
          <section class="widget widget--white widget--padding-20">
          <h3 class="widget__title">Other Properties</h3>

          <% Property.all.each do |property| %>
            <% if property != @property %>       
              <div class="similar-home">
                <a href="<%= property_path(property) %>">
                  <div class="similar-home__image">
                    <div class="similar-home__overlay"></div><!-- .similar-home__overlay -->
                    <%= image_tag 'uploads/manage-item-1.jpg', alt: 'Weston Hightpointe Place'%>
                    <span class="similar-home__favorite"><i class="fa fa-heart-o" aria-hidden="true"></i></span>
                  </div><!-- .similar-home__image -->
                  <div class="similar-home__content">
                    <h3 class="similar-home__title"><%= property.title %></h3>
                    <span class="similar-home__price"><%= property.property_price %></span>
                  </div>
                </a>
              </div>
            <% end %>
          <% end %>
          </section><!-- .widget -->
          </div>
        </aside >
      </div><!-- .row -->
    </div><!-- .container -->
  </div><!-- .property__container -->
</section><!-- .property -->