config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :list_furnitures
  resources :list_arts
  resources :list_sells
  resources :rental_lists
  mount ActionCable.server => '/cable'
  
  resources :notifications
  resources :profiles
  resources :properties
  devise_for :users
  resources :user do
    resources :services do
      member do
        post "mark_as_favorite"
      end
    end
  end
  root 'home#index'
  resources :chats, only: [:index, :show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'realtors' => 'pages#agents'
  get 'single_agent' => 'pages#single_agent'
  get 'list_rental' => 'pages#list_rental'
  get 'submit_property' => 'pages#submit_property'
  get 'property' => 'pages#property'
  get 'blog' => 'pages#blog'
  get 'single_blog' => 'pages#single_blog'
  get 'my_profile' => 'pages#my_profile'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'services' => 'pages#services'
  get 'my_property' => 'pages#my_property'
  get 'coming_soon' => 'pages#coming_soon'
  get 'book_marked_listing' => 'pages#book_marked_listing'
  get 'buy' => 'pages#buy'
  get 'sell' => 'pages#sell'
  get 'rent' => 'pages#rent'
  get 'property_detail' => 'pages#property_detail'
  get 'mortgage' => 'pages#mortgage' 
  get 'insurance' => 'pages#insurance' 
  get 'mobileApps' => 'pages#mobile_apps' 
  get 'hotels' => 'pages#hotels' 
  get 'partners' => 'pages#partners' 
  get 'investors' => 'pages#investors' 
  get 'team' => 'pages#team' 
  get 'travel' => 'pages#travel'
  get 'list_new' => 'pages#list_new'
  get '/buy/search' => 'pages#buy_search'
  get '/rent/search' => 'pages#rent_search'
  get '/services/search' => 'pages#services_search'
  get '/find-friend' => 'profiles#find_friends'
  get '/friend_list' => 'profiles#friend_list'
  post "profiles/add_friend" => "profiles#add_friend"
  post "profiles/remove_friend" => "profiles#remove_friend"
  get "/inbox" => "profiles#messages"
  get "art" => "pages#art"
  get "furniture" => "pages#furniture"
  post "switch_role" => "services#switch_role"

  get "/privacy-policy" => "pages#privacy_policy"
  get "/term_of_use" => "pages#term_of_use"
  get "/cookies-policy" => "pages#cookies_policy"

  resources :messages, only:[:create]
end

app/models/list_art.rb
class ListArt < ApplicationRecord
  belongs_to :user
end

app/controllers/list_arts_controller.rb
class ListArtsController < ApplicationController
  before_action :set_list_art, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /list_arts
  # GET /list_arts.json
  def index
    @list_arts = current_user.list_arts.all
  end

  # GET /list_arts/1
  # GET /list_arts/1.json
  def show
  end

  # GET /list_arts/new
  def new
    @list_art = current_user.list_arts.new
  end

  # GET /list_arts/1/edit
  def edit
  end

  # POST /list_arts
  # POST /list_arts.json
  def create
    @list_art = current_user.list_arts.new(list_art_params)

    respond_to do |format|
      if @list_art.save
        format.html { redirect_to list_arts_url, notice: 'List art was successfully created.' }
        format.json { render :show, status: :created, location: @list_art }
      else
        format.html { render :new }
        format.json { render json: @list_art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_arts/1
  # PATCH/PUT /list_arts/1.json
  def update
    respond_to do |format|
      if @list_art.update(list_art_params)
        format.html { redirect_to list_arts_url, notice: 'List art was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_art }
      else
        format.html { render :edit }
        format.json { render json: @list_art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_arts/1
  # DELETE /list_arts/1.json
  def destroy
    @list_art.destroy
    respond_to do |format|
      format.html { redirect_to list_arts_url, notice: 'List art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_art
      @list_art = ListArt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_art_params
      params.require(:list_art).permit(:art_name, :art_type, :price, :description, :size, :url)
    end
end

app/helpers/list_arts_helper.rb
module ListArtsHelper
end

app/views/list_arts/_art_card.html.erb
<div class="col-md-4 col-lg-3 col-sm-12 col-xs-12" style="padding: 1rem">
<div class="home-box" style="width: auto; padding: 0px; height: 265px;">
  <%= image_tag "uploads/manage-item-1.jpg" %>
  <h5> <%= f.art_name %></h5>
  <small><p> $ <%=  f.price %>  </p></small>
</div>
</div>

app/views/list_arts/_form.html.erb
<%= form_with(model: list_art, local: true) do |form| %>
 

  <div class="col-md-9">
   
  <% if list_art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list_art.errors.count, "error") %> prohibited this list_art from being saved:</h2>

      <ul>
      <% list_art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="submit-property__block">
        <h3 class="submit-property__headline">Add New Art</h3>
       
        <p>Name your art</p>
        <div class="row">
            <div class="col-md-12">
            <div class="submit-property__group">
              <%= form.text_field :art_name, class: "submit-property__field", placeholder: "Art name", :required => true  %>
            </div><!-- .submit-property__group -->
            </div><!-- .col -->
            

        </div><!-- .row -->
        <div class="row">
            <div class="col-md-6">
            <div class="submit-property__group">
              <%= form.text_field :art_type, class: "submit-property__field", placeholder: "Type" , :required => true  %>
            </div><!-- .submit-property__group -->
            </div><!-- .col -->
            
            <div class="col-md-6">
            <div class="submit-property__group">
              <%= form.text_field :size, class: "submit-property__field", placeholder: "Size ( L x W)" , :required => true  %>
            </div><!-- .submit-property__group -->
            </div><!-- .col -->
            
           
           
            

        </div><!-- .row -->

        
    </div><!-- .submit-property__block -->


    <div class="submit-property__block">
        <h3 class="submit-property__headline">Set your price</h3>
       
        <div class="row">
            <div class="col-md-4">
            <div class="submit-property__group">             
              <%= form.text_field :price , class: "submit-property__field", placeholder: "Price", :required => true  %>
            </div><!-- .submit-property__group -->
            </div><!-- .col -->
            

        </div><!-- .row -->

        <div class="row">
            <div class="col-md-8">
            <div class="submit-property__group">   
              <label for="property-title" class="submit-property__label">URL
              </label>
              <%= form.text_field :url , class: "submit-property__field", placeholder: "www.sample.com",  :required => true  %>
            </div><!-- .submit-property__group -->
            </div><!-- .col -->
            

        </div><!-- .row -->
        

        
    </div><!-- .submit-property__block -->


   


  


    <div class="submit-property__block">
        
        <div class="row">
            <div class="col-md-12">
            <div class="submit-property__group">
            <label for="submit-property-wysiwyg" class="submit-property__label">Description </label>
            <%= form.text_area :description, id: "submit-property-wysiwyg", required: true %>
            </div><!-- .submit-property__group -->
          </div><!-- .col -->
        </div><!-- .row -->

       
        
    </div><!-- .submit-property__block -->


   
  


    <div class="actions">
    <%= form.submit style: "    background: #ED4737;
    color: white;"%>
  </div>
  </div>
<% end %>

app/views/list_arts/_list_art_sidebar.html.erb
<div class="col-md-3">


<div class="settings-block">
    <span class="settings-block__title">Manage Art</span>
    <ul class="settings">
        
        <li class="setting <%= cp(list_arts_path)%>"><a href="<%= list_arts_path %>" class="setting__link"><i class="ion-ios-home-outline setting__icon"></i>My Art</a></li>
        <li class="setting <%= cp(new_list_art_path)%>"><a href="<%= new_list_art_path %>" class="setting__link"><i class="ion-ios-plus-outline setting__icon"></i>Add New Art</a></li>
        <li class="setting"><a href="/profiles" class="setting__link"><i class="ion-ios-undo-outline setting__icon"></i>Back</a></li>
    </ul>
</div>


</div>

app/views/list_arts/edit.html.erb
<section class="my-property">
<div class="container">
<ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
<li class="ht-breadcrumbs__item"><a href="/" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
<li class="ht-breadcrumbs__item"><a href="/profiles" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Profile</span></a></li>
<li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">Art</span></li>
</ul>
  <div class="my-profile__container">
    <div class="row">
      <%= render 'list_art_sidebar' %>
      <%= render 'form', list_art: @list_art %>            
    </div>
  </div>
</div>
</section>  

app/views/list_arts/index.html.erb
<section class="my-property">
  <div class="container">
    <ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
      <li class="ht-breadcrumbs__item"><a href="/" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
      <li class="ht-breadcrumbs__item"><a href="/profiles" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Profile</span></a></li>
      <li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">Art</span></li>
    </ul>
    <div class="my-profile__container">
      <div class="row">
      <%= render 'list_art_sidebar' %>
        <div class="col-md-9">
          <ul class="manage-list manage-list--my-property">
            <li class="manage-list__header">
              <span class="manage-list__title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> My List</span>
              <span class="manage-list__title"><i class="fa fa-calendar-o" aria-hidden="true"></i> Creation Date</span>
            </li>
            <% @list_arts.each do |list_art| %>
              <li class="manage-list__item">
              <div class="manage-list__item-container">
                <div class="manage-list__item-img">
                    <%= image_tag 'uploads/manage-item-1.jpg', alt: 'Weston Hightpointe Place', class: 'listing__img'%>
                </div><!-- manage-list__item-img -->
          
                <div class="manage-list__item-detail">
                  <h3 class="listing__title"><a href="#"><%= list_art.art_name %></a></h3>
                  <h6>$<%= list_art.price %></h6>
                </div>
              </div><!-- .manage-list__item-container -->
              <div class="manage-list__expire-date"><%= list_art.created_at.to_date %></div>
              
              <div class="manage-list__action">
                <td><%= link_to '<span class="edit"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</span>'.html_safe, edit_list_art_path(list_art) %></td>
                <%= link_to '<span class="remove"><i class="fa fa-times" aria-hidden="true"></i>Remove</span>'.html_safe, list_art, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </li><!-- .manage-list__item" -->
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/list_arts/new.html.erb
<section class="my-property">
<div class="container">
<ul class="ht-breadcrumbs ht-breadcrumbs--y-padding ht-breadcrumbs--b-border">
<li class="ht-breadcrumbs__item"><a href="/" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Home</span></a></li>
<li class="ht-breadcrumbs__item"><a href="/profiles" class="ht-breadcrumbs__link"><span class="ht-breadcrumbs__title">Profile</span></a></li>
<li class="ht-breadcrumbs__item"><span class="ht-breadcrumbs__page">Art</span></li>
</ul>
  <div class="my-profile__container">
    <div class="row">
      <%= render 'list_art_sidebar' %>
      <%= render 'form', list_art: @list_art %>            
    </div>
  </div>
</div>
</section>  

app/views/list_arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Art name:</strong>
  <%= @list_art.art_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @list_art.art_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @list_art.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list_art.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @list_art.size %>
</p>

<p>
  <strong>Url:</strong>
  <%= @list_art.url %>
</p>

<%= link_to 'Edit', edit_list_art_path(@list_art) %> |
<%= link_to 'Back', list_arts_path %>